- name: Import rpm key
  rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: Remote kernel repo
  yum:
    name: http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
    state: present

- name: install the latest version of Kernel from remote repo
  yum:
    name: kernel-ml
    enablerepo: elrepo-kernel
    state: present

#- lineinfile: 'dest=/etc/default/grub line=GRUB_DEFAULT=0'
#  notify: update-grub

- name: Change GRUB policy
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_DEFAULT(.*)'
    replace: 'GRUB_DEFAULT=0'
  notify: update grub2 
